### ISSUE TITLE
sphinxcontrib-mermaid 1.0.0 HTML rendering incorrect compared to 0.9.2

### ISSUE THREAD

**Issue by lytn1ng** [mgaitan/sphinxcontrib-mermaid#163]
Here is an example diagram - note that the connectors are arrow-less:
```mermaid
---
caption: Test Diagram
---
flowchart TD;
%%flowchart-elk TD;
id1("One")---id2("Two");
id1("One")---id3("Three");
```
Here's how the HTML renders with sphinxcontrib-mermaid 0.9.2:

![image](https://github.com/user-attachments/assets/879e818e-755d-464d-8aeb-ff093c0c390c)

1. The diagram appears to be rendered directly on the dark background (i.e. no colored box).
2. The connector lines are visible even in dark mode

However, with 1.0.0, here's how it looks:
![image](https://github.com/user-attachments/assets/41f9319f-fc94-409c-80b8-151d17d3ee59)

1. There's a gray-ish box around the diagram
3. There are no connectors visible in dark mode

And this is how it looks with 1.0.0 in Light mode:
![image](https://github.com/user-attachments/assets/c390e000-bb3f-4a03-8273-3fda71af9772)

1. There is still a gray-ish box around the diagram
2. The connectors are visible - but they have arrows

Please fix this. issue But for now, 0.9.2 still works well enough with Sphinx 8.1.3.

**Comment by timkpaine** [comment]
This is not what it looks like for me, cannot reproduce. Please provide code or if you’re using any customizations.

**Comment by lytn1ng** [comment]
Thanks for the quick response, @timkpaine.

What **does** it look like for you?

I had included the code in my original issue report but it has been converted to a diagram. I am adding it here again without the back-ticks  (hopefully it's readable)

---
mermaid
flowchart TD;
%%flowchart-elk TD;
id1("One")---id2("Two");
id1("One")---id3("Three");
---

As for customizations: I'm not using anything for mermaid. I am using Sphinx, myst-parser, ablog and the sphinx-book-theme.

In my testing, the only things I did were:
pip install sphinxcontrib-mermaid (this installed 1.0.0).

The HTML diagram looked odd.

Then, I did
pip uninstall sphinxcontrib-mermaid
pip install sphinxcontrib-mermaid==0.9.2

And then I ran the "make html" command - the diagram looked ok again in the HTML.

**Comment by timkpaine** [comment]
Furo:
<img width="287" alt="Screenshot 2024-11-10 at 23 31 09" src="https://github.com/user-attachments/assets/67b1f8b6-5696-4faf-9d7d-0c9db2bdefad">
<img width="284" alt="Screenshot 2024-11-10 at 23 31 16" src="https://github.com/user-attachments/assets/6df6cfb7-587a-4211-9756-ef51895807e8">

sphinx-book-theme:
<img width="444" alt="Screenshot 2024-11-10 at 23 40 38" src="https://github.com/user-attachments/assets/376f8c8b-0b8f-4873-a0f3-c072fb5593a0">
<img width="335" alt="Screenshot 2024-11-10 at 23 40 42" src="https://github.com/user-attachments/assets/348041ca-b5b0-42c7-b556-e3255f854dc9">


css rule causing the problem:
<img width="343" alt="Screenshot 2024-11-10 at 23 40 56" src="https://github.com/user-attachments/assets/d57afcbc-f552-48d8-be7b-e94765c8c9b8">
 
We render in `pre` tag since https://github.com/mgaitan/sphinxcontrib-mermaid/pull/133

**Comment by lytn1ng** [comment]
Thank you, @timkpaine.

I think your results match mine - at least with the sphinx-book-theme.

However, the rendering is still wrong in 1.0.0 - even in Furo - since the connecting lines have arrows. According to the code, there should be no arrows.

Whereas, irrespective of the CSS, it works in 0.9.2. The connecting lines have no arrows when using 0.9.2.

**Comment by timkpaine** [comment]
The code should have arrows, I don't see anything wrong. [mermaid live link](https://mermaid.live/edit#pako:eNptjTELgzAQRv-KHAgtmKHtlq7uHepUshzmNEGTk5ggRfzvTZE6dbv33ge3QsuaQEI38tIaDLFo6rvyZXkIQeOwS6svJwUPTwrOQgirrxmbhTP-q7dvNYFo71CBo-DQ6vxuVb4oFERDLmeZT41hUKD8lneYIj_fvgUZQ6IKAqfegOxwnDOlSWOk2mIf0B12Qv9i_vH2AVgMRpQ)
