### ISSUE TITLE
Load mermaid.min.js conditionally?

### ISSUE THREAD

**Issue by segfaultxavi** [mgaitan/sphinxcontrib-mermaid#80]
As soon as the sphinxcontrib-mermaid extension is enabled in `conf.py`, ALL generated html files load `mermaid.min.js` whether they include a Mermaid directive or not:

```html
<script src="https://unpkg.com/mermaid/dist/mermaid.min.js"></script>
```

This file is about 1MB in size, not much, but currently the biggest file my site loads. 99% of the time there's no need for it since I don't have that many Mermaid diagrams.

This has been flagged by Lighthouse as an Opportunity and I agree with it :)

I don't think it's too hard to make the load of this javascript conditional to the Mermaid directive being actually used in a page?

**Comment by hugovk** [comment]
I've found a workaround: use an empty JavaScript file that is inserted into all pages, and manually add the real JS only to the pages using Mermaid.

1. Set `mermaid_version = ""` to use a local version, but instead of using a real version, use an empty `mermaid.js` file.
2. Then on the pages using Mermaid, load a real JavaScript file using the `.. raw:: html` directive.
3. This could either be a remote file, or as shown below, a local `mermaid.min.js` -- note the `.min.` to differentiate it from the empty version. 
4. Optionally also set `mermaid_init_js = ""` because we don't need that on every page, and also include it in the `.. raw:: html` section of the Mermaid page.

Example:

```javascript
// _static/js/mermaid.js

// Intentionally empty; the extension adds this to every page.
// We'll instead manually add mermaid.min.js to only the pages
// that need it.
```

```javascript
// _static/js/mermaid.min.js

// [This is the full mermaid.min.js file from https://unpkg.com/browse/mermaid/ ]
```

```python
# conf.py

html_js_files = [
    "js/mermaid.js",
]

# sphinxcontrib.mermaid
mermaid_version = ""
mermaid_init_js = ""
```

```rst
.. my-page-using-mermaid.rst

My Page Using Mermaid
=====================

.. mermaid:: my-mermaid-file.mmd

.. raw:: html

    <script src="_static/js/mermaid.min.js"></script>
    <script>mermaid.initialize({startOnLoad:true});</script>
```
